steps:
  check:
    image: denoland/deno:alpine-2.5.0
    when:
      event: [push, pull_request, tag]
    commands:
      - deno --version
      - deno fmt --check
      - deno lint
      - deno check
      - deno test -A --no-check
      - deno task build

  release:
    image: denoland/deno:alpine-2.5.0
    when:
      event: [tag]
      tag: v*
    commands:
      - deno task build
      - docker build -t antonshubin/mig:${CI_COMMIT_TAG} -t antonshubin/mig:latest .
      - docker push antonshubin/mig:${CI_COMMIT_TAG}
      - docker push antonshubin/mig:latest
    secrets: [docker_username, docker_password]
