steps:
  check:
    image: denoland/deno:alpine-2.5.0
    when:
      event: [push, pull_request, tag]
    commands:
      - deno --version
      - deno fmt --check
      - deno lint
      - deno check
      - deno test -A --no-check
      - deno task build

  release:
    image: denoland/deno:alpine-2.5.0
    when:
      event: [tag]
      tag: v*
    commands:
      - deno install -A -r jsr:@david/ghcr-tag-publish
      - deno task build
      - docker build -t ghcr.io/spy4x/mig:${CI_COMMIT_TAG} -t ghcr.io/spy4x/mig:latest .
      - docker push ghcr.io/spy4x/mig:${CI_COMMIT_TAG}
      - docker push ghcr.io/spy4x/mig:latest
    secrets: [docker_username, docker_password]
